package com.model.pojo;
// Generated Oct 20, 2020 1:17:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GroupTb generated by hbm2java
 */
public class GroupTb  implements java.io.Serializable {


     private Integer id;
     private String groupName;
     private int groupOwner;
     private Set<GroupChatTb> groupChatTbs = new HashSet<GroupChatTb>(0);
     private Set<GroupUserTb> groupUserTbs = new HashSet<GroupUserTb>(0);

    public GroupTb() {
    }

	
    public GroupTb(String groupName, int groupOwner) {
        this.groupName = groupName;
        this.groupOwner = groupOwner;
    }
    public GroupTb(String groupName, int groupOwner, Set<GroupChatTb> groupChatTbs, Set<GroupUserTb> groupUserTbs) {
       this.groupName = groupName;
       this.groupOwner = groupOwner;
       this.groupChatTbs = groupChatTbs;
       this.groupUserTbs = groupUserTbs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public int getGroupOwner() {
        return this.groupOwner;
    }
    
    public void setGroupOwner(int groupOwner) {
        this.groupOwner = groupOwner;
    }
    public Set<GroupChatTb> getGroupChatTbs() {
        return this.groupChatTbs;
    }
    
    public void setGroupChatTbs(Set<GroupChatTb> groupChatTbs) {
        this.groupChatTbs = groupChatTbs;
    }
    public Set<GroupUserTb> getGroupUserTbs() {
        return this.groupUserTbs;
    }
    
    public void setGroupUserTbs(Set<GroupUserTb> groupUserTbs) {
        this.groupUserTbs = groupUserTbs;
    }




}


