package com.model.pojo;
// Generated Oct 20, 2020 1:17:42 PM by Hibernate Tools 4.3.1



/**
 * UserFriendTb generated by hbm2java
 */
public class UserFriendTb  implements java.io.Serializable {


     private Integer id;
     private UsersTb usersTbByAddee;
     private UsersTb usersTbByAdder;

    public UserFriendTb() {
    }

    public UserFriendTb(UsersTb usersTbByAddee, UsersTb usersTbByAdder) {
       this.usersTbByAddee = usersTbByAddee;
       this.usersTbByAdder = usersTbByAdder;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UsersTb getUsersTbByAddee() {
        return this.usersTbByAddee;
    }
    
    public void setUsersTbByAddee(UsersTb usersTbByAddee) {
        this.usersTbByAddee = usersTbByAddee;
    }
    public UsersTb getUsersTbByAdder() {
        return this.usersTbByAdder;
    }
    
    public void setUsersTbByAdder(UsersTb usersTbByAdder) {
        this.usersTbByAdder = usersTbByAdder;
    }




}


